spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boatrentalservicedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true

  graphql:
    path: /graphql
    graphiql:
      enabled: true