spring:

#  Database configuration
  datasource:
    url: jdbc:postgresql://dev-db:5432/devbrsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

#  Liquibase configuration
  liquibase:
    enabled: true
    change-log: db/changelogs.yaml
